definitions:
  domain.Advertisement:
    description: Advertisement structure with detailed advertisement information.
    properties:
      activeFlag:
        type: boolean
      additionalInfo:
        type: string
      advertisementDate:
        description: Pointer to time.Time for optional dates
        type: string
      advertisementType:
        type: string
      advertiserId:
        type: integer
      availabilityDate:
        type: string
      city:
        type: string
      clientId:
        type: integer
      dailyPrice:
        description: Using float32 for prices
        type: number
      description:
        type: string
      favoriteFlag:
        type: boolean
      hourlyPrice:
        type: number
      id:
        type: string
      keywords:
        items:
          type: string
        type: array
      latitude:
        type: number
      limit:
        type: integer
      location:
        allOf:
          - $ref: "#/definitions/domain.Location"
        description: Replaces separate Latitude and Longitude fields
      longitude:
        type: number
      miles:
        type: number
      monthlyPrice:
        type: number
      municipality:
        type: string
      neighborhood:
        type: string
      number:
        type: string
      period:
        type: string
      periodPrice:
        type: number
      photos:
        description:
          Assuming Photos is an array of string. Adjust if the structure
          is different.
        items:
          type: string
        type: array
      priceFrom:
        type: number
      priceUntil:
        type: number
      size:
        type: string
      state:
        type: string
      street:
        type: string
      title:
        type: string
      validAdvertisementFrom:
        type: string
      validAdvertisementUntil:
        type: string
      weeklyPrice:
        type: number
      yearlyPrice:
        type: number
      zipCode:
        type: string
    type: object
  domain.Location:
    properties:
      coordinates:
        description: longitude, latitude order
        items:
          type: number
        type: array
      type:
        type: string
    type: object
  handlers.GeoLocationRequest:
    properties:
      latitude:
        type: number
      longitude:
        type: number
      maxDistance:
        description: In Kilometers, fixed typo in struct tag
        type: integer
    type: object
info:
  contact: {}
paths:
  /search:
    post:
      consumes:
        - application/json
      description:
        Searches for advertisements by longitude, latitude, and maximum
        distance.
      parameters:
        - description: Geo Location Request
          in: body
          name: geoLocationRequest
          required: true
          schema:
            $ref: "#/definitions/handlers.GeoLocationRequest"
      produces:
        - application/json
      responses:
        "200":
          description: A list of advertisements within max distance
          schema:
            items:
              $ref: "#/definitions/domain.Advertisement"
            type: array
      summary: Search by geo location with max distance
      tags:
        - advertisement
  /{longitude}/{latitude}:
    get:
      consumes:
        - application/json
      description: Searches for advertisements by longitude and latitude.
      parameters:
        - description: Longitude
          in: path
          name: longitude
          required: true
          type: number
        - description: Latitude
          in: path
          name: latitude
          required: true
          type: number
      produces:
        - application/json
      responses:
        "200":
          description: A list of advertisements
          schema:
            items:
              $ref: "#/definitions/domain.Advertisement"
            type: array
      summary: Search by geo location
      tags:
        - advertisement
swagger: "2.0"
